### ISSUE TITLE
Unable to Load/Paste Source Groups

### ISSUE THREAD

**Issue by NelanaSnow** [exeldro/obs-source-copy#1]
Was attempting to copy a group of sources over to another scene collection, and was able to save the group to a .json file easily enough, but when I get over to the new scene collection, at no point do I see a "Paste/Load Group" Option, and trying the other load/paste options to be safe doesn't yield any results.

Image of the Options Listed in the menu.
[https://i.imgur.com/sYxff1q.png](url)

**Comment by exeldro** [comment]
you are correct that is an oversight from me, will add that in

**Comment by NelanaSnow** [comment]
So After a bit more testing, I did find a workaround.
If you create a blank group, and name it the same as the one originally copied/saved, then the "Load/Paste Source" option on that group will actually work.

Either way, Thanks for the fast response, and thank you so much for the awesome Plugin!

**Comment by djd007** [comment]
Also similarly if you save a Scene that has any Groups in the Sources then try to load it back - the Groups will be empty.   It seems like the groups aren't transferring over if you copy/paste or if you save/load.
