### ISSUE TITLE
Source Copy not available on 31.0.0-beta1 (64 bit)

### ISSUE THREAD

**Issue by djd007** [exeldro/obs-source-copy#11]
The menu option for Source Copy is not showing up in the menu on OBS 31.0.0-beta1.  The only message I see in the log file that looks related is:

Module '../../obs-plugins/64bit/source-copy.dll' not loaded

**Comment by exeldro** [comment]
Can you try if this build works correctly for you?
https://github.com/exeldro/obs-source-copy/actions/runs/11274264411

**Comment by djd007** [comment]
That worked for me, and an initial testing of using it seems to work fine.  Thanks exeldro!
