### ISSUE TITLE
Log messages for config function say "Aitum Multistream"

### ISSUE THREAD

**Issue by YorVeX** [exeldro/obs-source-copy#12]
Came with [this commit](https://github.com/exeldro/obs-source-copy/commit/e30b36863e8ef5193c0f8249930898cd0116100d#diff-bdfde06bbec051f4249bebb3387741f5427057b7aa8d7e290d48899f5a5ae20f), obviously a copy-paste error from your original commit for the Aitum Multistream plugin 😅

**Comment by exeldro** [comment]
Fixed in master
